import { Footer } from "@/components/Footer/Footer";
import { Navbar } from "@/components/Navbar/Navbar";
import { Inter, Roboto_Slab } from "next/font/google";
import "./styles.css";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Welcome to student-portal",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${robotoSlab.variable} ${inter.className}`}>
      <body>
        <header>
          <Navbar />
        </header>
        <main className="mt-20">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
