import { SessionProvider } from "next-auth/react";
import { IBM_Plex_Sans, Roboto_Slab } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./styles.css";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
});
const ibmPlex = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex",
});

export const metadata = {
  title: "Welcome to student-portal",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${robotoSlab.variable} ${ibmPlex.className}`}>
      <SessionProvider>
        <body>
          {children}
          <ToastContainer
            position="top-center"
            autoClose={4000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss={false}
            theme="light"
          />
        </body>
      </SessionProvider>
    </html>
  );
}
