import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "./global.css";

export const metadata = {
  title: "Welcome to admin-panel",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <body>
            {children}
            <ToastContainer
              position="top-center"
              autoClose={4000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss={false}
              theme="light"
            />
          </body>
        </SessionProvider>
      </body>
    </html>
  );
}
